#!/bin/zsh

setopt +o nomatch
rm -f **/.DS_Store
setopt -o nomatch

for workflow in *; do
	if [ ! -d "$workflow" ] || [ "$workflow" = "script" ]; then
		continue
	fi

	version="$(plutil -extract version raw -o - Length/info.plist)"
	echo -n "Building $workflow v$version... "
	rm -f "$workflow.alfredworkflow"
	(cd "$workflow" && zip -9qr "../$workflow.alfredworkflow" .)

	if [ $? -eq 0 ]; then
		echo "\033[32mdone\033[0m"
	else
		echo "\033[31mFAILED\033[0m"
	fi
done

