#!/bin/zsh

for file in *.alfredworkflow; do
	echo -n "Extracting $file... "

	name="$(basename "$file" .alfredworkflow)"

	rm -rf "$name/"

	unzip -xoq "$file" -d "$name/"

	if [ $? -eq 0 ]; then
		echo "\033[32mdone\033[0m"
	else
		echo "\033[31mFAILED\033[0m"
	fi
done

script/format
